        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "background": "var(--background)",
                        "on-background": "var(--on-background)",
                        "surface": "var(--surface)",
                        "on-surface": "var(--on-surface)",
                        "surface-variant": "var(--surface-variant)",
                        "on-surface-variant": "var(--on-surface-variant)",
                        "surface-container": "var(--surface-container)",
                        "surface-container-low": "var(--surface-container-low)",
                        "surface-container-high": "var(--surface-container-high)",
                        "surface-container-highest": "var(--surface-container-highest)",
                        "surface-container-lowest": "var(--surface-container-lowest)",
                        "primary": "var(--primary)",
                        "on-primary": "var(--on-primary)",
                        "primary-container": "var(--primary-container)",
                        "on-primary-container": "var(--on-primary-container)",
                        "secondary": "var(--secondary)",
                        "on-secondary": "var(--on-secondary)",
                        "secondary-container": "var(--secondary-container)",
                        "on-secondary-container": "var(--on-secondary-container)",
                        "outline": "var(--outline)",
                        "outline-variant": "var(--outline-variant)",
                        "surface-bright": "var(--surface-bright)",
                        "surface-dim": "var(--surface-dim)",
                        "error": "var(--error)",
                        "on-error": "var(--on-error)",
                        "error-container": "var(--error-container)",
                        "on-error-container": "var(--on-error-container)",
                        "tertiary": "var(--tertiary)",
                        "on-tertiary": "var(--on-tertiary)",
                        "tertiary-container": "var(--tertiary-container)",
                        "on-tertiary-container": "var(--on-tertiary-container)",
                        "on-primary-fixed": "#0d1c32",
                        "tertiary-fixed-dim": "#bcc7dd",
                        "inverse-on-surface": "#2e3132",
                        "secondary-fixed": "#ffdea5",
                        "inverse-primary": "#515f78",
                        "inverse-surface": "#e1e3e4",
                        "tertiary-fixed": "#d8e3fa",
                        "on-secondary-fixed-variant": "#5d4201",
                        "on-secondary-fixed": "#261900",
                        "primary-fixed": "#d6e3ff",
                        "on-tertiary-fixed-variant": "#3c475a",
                        "secondary-fixed-dim": "#e9c176",
                        "surface-tint": "#b9c7e4",
                        "primary-fixed-dim": "#b9c7e4",
                        "on-tertiary-fixed": "#111c2c",
                        "on-primary-fixed-variant": "#39475f"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.375rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "unit": "4px",
                        "margin-desktop": "48px",
                        "gutter": "24px",
                        "container-max": "1280px",
                        "margin-mobile": "16px"
                    },
                    "fontFamily": {
                        "display-lg": ["\"Source Serif 4\""],
                        "body-lg": ["Manrope"],
                        "body-md": ["Manrope"],
                        "label-sm": ["Manrope"],
                        "headline-lg-mobile": ["\"Source Serif 4\""],
                        "headline-lg": ["\"Source Serif 4\""]
                    },
                    "fontSize": {
                        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
                        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
                        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
                        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }]
                    }
                },
            },
        }